import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
const $=s=>document.querySelector(s),clamp=T.MathUtils.clamp;
let low=innerWidth<700,started=false,paused=matchMedia('(prefers-reduced-motion:reduce)').matches,frame,last=0,time=0,yaw=0,pitch=.06,drag=null,failed=false;
const keys=new Set(),touch=new Set(),obstacles=[],staticGroups=new Map(),flames=[],lamps=[],wind=[];
let seed=930;function random(){seed=(seed*16807)%2147483647;return seed/2147483647;}
const renderer=new T.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.4));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;$('#view').append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color(0x758482);scene.fog=new T.FogExp2(0x82918c,.012);
const camera=new T.PerspectiveCamera(64,innerWidth/innerHeight,.08,180);camera.position.set(.8,1.76,16);yaw=.025;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));
const ao=new SSAOPass(scene,camera,innerWidth,innerHeight);ao.kernelRadius=.65;ao.minDistance=.003;ao.maxDistance=.20;ao.enabled=!low;composer.addPass(ao);
const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.28,.5,1.5);composer.addPass(bloom);composer.addPass(new SMAAPass());composer.addPass(new OutputPass());
const hemi=new T.HemisphereLight(0xc9e0e4,0x39442d,.9);scene.add(hemi);
const sun=new T.DirectionalLight(0xffe2b3,2.3);sun.position.set(-19,32,4);sun.castShadow=true;sun.shadow.mapSize.set(low?1024:2048,low?1024:2048);Object.assign(sun.shadow.camera,{left:-23,right:23,top:24,bottom:-25,near:1,far:90});sun.shadow.normalBias=.025;sun.shadow.bias=-.00005;sun.target.position.set(0,0,-8);scene.add(sun,sun.target);
const manager=new T.LoadingManager();let assetsDone=false;manager.onProgress=(url,done,total)=>{$('#progress').value=Math.min(97,done/total*95);$('#loading').textContent=`Loading stone, foliage and lighting · ${Math.round(done/total*100)}%`;};
const textureLoader=new T.TextureLoader(manager),gltfLoader=new GLTFLoader(manager),draco=new DRACOLoader(manager);draco.setDecoderPath('../temple/vendor/draco/');gltfLoader.setDRACOLoader(draco);
async function surface(name,scale=1){const textures=await Promise.all(['color','normal','rough'].map(map=>textureLoader.loadAsync(`assets/${name}/${map}${low?'-1k':''}.webp`)));textures.forEach(t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());});textures[0].colorSpace=T.SRGBColorSpace;return new T.MeshStandardMaterial({map:textures[0],normalMap:textures[1],roughnessMap:textures[2],normalScale:new T.Vector2(scale,scale),roughness:1,color:0xffffff});}
function projectUV(g,tile=.4){const p=g.attributes.position,n=g.attributes.normal,uv=g.attributes.uv;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),nx=Math.abs(n.getX(i)),ny=Math.abs(n.getY(i)),nz=Math.abs(n.getZ(i));uv.setXY(i,(nx>ny&&nx>nz?z:x)*tile,(ny>nx&&ny>nz?z:y)*tile);}return g;}
function add(g,m,pos=[0,0,0],rotation=[0,0,0],scale=[1,1,1],batch=true){const o=new T.Mesh(g,m);o.position.set(...pos);o.rotation.set(...rotation);o.scale.set(...scale);o.castShadow=true;o.receiveShadow=true;if(batch){o.updateMatrix();let copy=g.clone();if(copy.index)copy=copy.toNonIndexed();copy.applyMatrix4(o.matrix);copy.deleteAttribute('tangent');if(!staticGroups.has(m))staticGroups.set(m,[]);staticGroups.get(m).push(copy);}else scene.add(o);return o;}
const boxCache=new Map();function block(x,y,z,w,h,d,mat,bevel=.05,tile=.45){const key=[w,h,d,bevel,tile].join(',');if(!boxCache.has(key))boxCache.set(key,projectUV(new RoundedBoxGeometry(w,h,d,2,Math.min(bevel,Math.min(w,h,d)*.2)),tile));return add(boxCache.get(key),mat,[x,y,z]);}
function collider(x,z,w,d){obstacles.push({x,z,w:w/2,d:d/2});}
function shaft(x,z,mat){const points=[[0,.52],[.1,.52],[.17,.44],[.24,.44],[.3,.34],[.4,.34],[.47,.39],[.56,.39],[.62,.28],[.75,.28],[.8,.32],[.88,.32],[.96,.25],[3.4,.22],[3.48,.30],[3.60,.30],[3.67,.40],[3.80,.40],[3.87,.52],[4.02,.52]].map(([y,r])=>new T.Vector2(r,y));const g=projectUV(new T.LatheGeometry(points,32),.8);add(g,mat,[x,.05,z]);block(x,.11,z,1.15,.22,1.15,mat);block(x,4.16,z,1.2,.24,1.2,mat);for(let a=0;a<12;a++){const angle=a*Math.PI/6;const flute=new T.CylinderGeometry(.043,.052,2.2,6);add(flute,mat,[x+Math.cos(angle)*.248,2.13,z+Math.sin(angle)*.248]);}collider(x,z,.9,.9);}
// Continuous sculpted lotus relief rather than separate balls glued to flat boxes.
function relief(){const g=new T.PlaneGeometry(1,1,48,48),p=g.attributes.position;for(let i=0;i<p.count;i++){let x=p.getX(i)*2,y=p.getY(i)*2,r=Math.hypot(x,y),a=Math.atan2(y,x);const petal=Math.pow(Math.max(0,Math.cos(a*8)),2);const ring=Math.exp(-Math.pow((r-.59)/.19,2))*(.35+.65*petal);const inner=Math.exp(-Math.pow((r-.29)/.10,2))*(.4+.6*Math.pow(Math.cos(a*6+.7),2));let h=.12*ring+.07*inner+.11*Math.exp(-r*r/.025)+.035*Math.exp(-Math.pow((r-.91)/.045,2));h+=.004*Math.sin(x*53)*Math.sin(y*47);p.setZ(i,h);}g.computeVertexNormals();return g;}
const lotus=relief();
let stone,sand,floor,soil,brass,black;
function architecture(){
  // Individual uneven paving and deep joints provide real silhouette and contact shadows.
  for(let x=-8;x<=8;x+=2)for(let z=-2;z<=16;z+=2){block(x,.015+(random()-.5)*.014,z,1.96,.14,1.96,floor,.035,.28);}
  block(0,-.16,5,20,.22,26,stone);collider(-9.9,5,.5,27);collider(9.9,5,.5,27);
  for(const side of [-1,1]){for(let z=-5;z<=17;z+=2.2){block(side*9.7,.65,z,.7,1.3,2.15,stone);block(side*9.7,1.35,z,.86,.14,2.2,sand);if(z<13)shaft(side*8.1,z,sand);}block(side*8.1,4.48,4,3.1,.38,22,sand);block(side*8.1,4.77,4,3.35,.16,22.3,stone);}
  // Portal piers, inset panels and detailed mouldings establish the gateway silhouette.
  for(const side of [-1,1]){block(side*3.55,2.4,-6,3.1,4.8,4.5,stone,.12);collider(side*3.55,-6,3.1,4.5);shaft(side*2.25,-3.45,sand);shaft(side*4.7,-3.45,sand);for(let y=.5;y<4.7;y+=.9){block(side*3.55,y,-3.65,1.2,.82,.12,sand,.02);add(lotus,sand,[side*3.55,y,-3.57],[0,0,0],[.9,.7,1]);}for(const y of [.2,.48,4.45,4.75])block(side*3.55,y,-6,3.35,.17,4.7,sand);}
  block(0,4.94,-6,10.7,.45,4.85,sand);block(0,5.28,-6,11.2,.2,5.15,sand);
  for(let level=0;level<6;level++){const y=5.62+level*1.37,w=10.45-level*1.17,d=4.6-level*.40;block(0,y+.39,-6,w,.9,d,stone,.10);for(const off of [-.1,.03,.91,1.06])block(0,y+off,-6,w+.30+(off>.9?.22:0),.12,d+.27,sand);const count=9-level;for(let i=0;i<count;i++){const x=(i-(count-1)/2)*(w-.6)/count;block(x,y+.40,-6+d/2+.06,.79,.77,.21,black,.02);add(lotus,sand,[x,y+.4,-6+d/2+.19],[0,0,0],[.66,.67,1]);const arch=new T.TorusGeometry(.37,.085,8,24,Math.PI);add(arch,sand,[x,y+.61,-6+d/2+.10]);for(const side of [-1,1])block(x+side*.37,y+.29,-6+d/2+.1,.13,.57,.19,sand,.03);block(x,y-.03,-6+d/2+.12,.9,.1,.3,sand);}}
  block(0,14.04,-6,4,.26,2.45,sand);for(let i=-2;i<=2;i++){add(new T.LatheGeometry([new T.Vector2(.13,0),new T.Vector2(.25,.15),new T.Vector2(.19,.36),new T.Vector2(.06,.46),new T.Vector2(.015,.72)],24),brass,[i*.72,14.18,-6]);}
  // Beyond the gate: a walkable stone hall and a restrained sacred centre.
  block(0,.15,-15,12,.30,15,stone);for(let x=-4;x<=4;x+=2)for(let z=-10;z>=-20;z-=2)block(x,.33,z,1.97,.1,1.97,floor,.025,.3);
  for(const side of [-1,1]){block(side*5.4,2.7,-15,.7,5.1,15,stone);collider(side*5.4,-15,.7,15);for(let z=-10;z>=-20;z-=3.3)shaft(side*3.8,z,sand);block(side*3.8,4.45,-15,2.3,.3,14,sand);}block(0,4.85,-16,11.2,.55,12,stone);block(0,2.7,-22,11,5.1,.7,stone);collider(0,-22,11,.7);
  for(let j=0;j<4;j++)block(0,.1+j*.065,-2.7-j*.45,4.2,.2+j*.10,.6,sand);
  for(const side of [-1,1]){block(side*2.7,2.4,-18.9,2.8,4.1,.55,stone);collider(side*2.7,-18.9,2.8,.55);for(let y=.7;y<4.5;y+=.55)add(lotus,sand,[side*1.2,y,-18.5],[0,0,0],[.4,.42,.6]);}block(0,4.53,-18.9,8.5,.32,.7,sand);
  add(new T.CylinderGeometry(1.35,1.5,.4,64),black,[0,.6,-20.3]);add(new T.CylinderGeometry(.97,1.15,.28,64),black,[0,.94,-20.3]);add(new T.TorusGeometry(1.02,.06,10,64),brass,[0,1.10,-20.3],[Math.PI/2,0,0]);
  const lingam=new T.LatheGeometry([new T.Vector2(0,0),new T.Vector2(.44,0),new T.Vector2(.44,1.13),new T.Vector2(.43,1.27),new T.Vector2(.37,1.40),new T.Vector2(.25,1.51),new T.Vector2(0,1.56)],64);add(lingam,black,[0,1.04,-20.3]);collider(0,-20.3,2.5,2.5);
  const ash=new T.MeshStandardMaterial({color:0xdad2b9,roughness:.85});for(const y of [1.80,1.94,2.08])add(new T.TorusGeometry(.446,.016,8,32,1.16),ash,[0,y,-20.3],[Math.PI/2,0,Math.PI*.32]);
  const flower=new T.MeshStandardMaterial({color:0xc38323,roughness:1});for(let i=0;i<55;i++){const a=i*Math.PI*2/55;add(new T.IcosahedronGeometry(.07,1),flower,[Math.cos(a)*.9,1.14,-20.3+Math.sin(a)*.9]);}
  // Worn freestanding relief slabs along the courtyard walls.
  for(const side of [-1,1])for(let z of [1,6,11]){block(side*9,2.35,z,.18,1.5,1.6,sand);add(lotus,sand,[side*8.87,2.35,z],[0,-side*Math.PI/2,0],[1.32,1.32,1.2]);}
}
let gates=[];function doors(){for(const side of [-1,1]){const pivot=new T.Group();pivot.position.set(side*1.8,.3,-4.25);const panel=new T.Mesh(new RoundedBoxGeometry(1.77,4.0,.16,2,.04),brass);panel.position.set(-side*.88,2,0);pivot.add(panel);for(let row=0;row<5;row++){const inset=new T.Mesh(new RoundedBoxGeometry(1.45,.64,.05,2,.03),black);inset.position.set(-side*.88,.4+row*.78,.105);pivot.add(inset);const r=new T.Mesh(lotus,brass);r.position.set(-side*.88,.4+row*.78,.15);r.scale.set(1.2,.6,1);pivot.add(r);}scene.add(pivot);gates.push({pivot,side});}}
function glow(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,236,186,1)');g.addColorStop(.15,'rgba(255,170,60,.6)');g.addColorStop(.6,'rgba(255,130,25,.03)');g.addColorStop(1,'rgba(255,130,25,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new T.CanvasTexture(c);}
const glowMap=glow();
function torch(x,z){const base=new T.MeshStandardMaterial({color:0x332a1c,metalness:.8,roughness:.5});add(new T.LatheGeometry([new T.Vector2(.28,0),new T.Vector2(.3,.08),new T.Vector2(.14,.18),new T.Vector2(.06,.32),new T.Vector2(.05,1.17),new T.Vector2(.19,1.25),new T.Vector2(.26,1.34)],20),base,[x,.11,z]);const f=new T.Mesh(new T.SphereGeometry(.07,12,8),new T.MeshBasicMaterial({color:0xffbb54}));f.position.set(x,1.54,z);f.scale.set(1,2.1,1);scene.add(f);flames.push(f);const sprite=new T.Sprite(new T.SpriteMaterial({map:glowMap,transparent:true,blending:T.AdditiveBlending,depthWrite:false,color:0xffae59,opacity:.6}));sprite.position.copy(f.position);sprite.scale.set(1.3,1.8,1);scene.add(sprite);const l=new T.PointLight(0xffa348,9,7,2);l.position.set(x,1.7,z);scene.add(l);lamps.push(l);collider(x,z,.4,.4);}
function batches(){for(const [mat,geos]of staticGroups){const merged=mergeGeometries(geos,false);if(!merged)throw Error('Geometry batching failed');const m=new T.Mesh(merged,mat);m.castShadow=m.receiveShadow=true;scene.add(m);geos.forEach(g=>g.dispose());}staticGroups.clear();}
function normalize(model){model.updateMatrixWorld(true);const b=new T.Box3().setFromObject(model),size=b.getSize(new T.Vector3()),center=b.getCenter(new T.Vector3());model.position.sub(new T.Vector3(center.x,b.min.y,center.z));const group=new T.Group();group.add(model);group.userData.height=size.y;return group;}
function plant(template,x,z,height,rotation=0){const o=template.clone(true),s=height/template.userData.height;o.scale.setScalar(s);o.position.set(x,0,z);o.rotation.y=rotation;o.traverse(m=>{if(m.isMesh){m.castShadow=m.receiveShadow=true;}});scene.add(o);return o;}
function windMaterial(m){if(m.userData.wind)return;m.userData.wind=true;m.onBeforeCompile=shader=>{shader.uniforms.uWind={value:0};wind.push(shader.uniforms.uWind);shader.vertexShader='uniform float uWind;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.x += sin(uWind*.7+position.y*1.3+position.x)*.022*smoothstep(0.,1.,position.y);');};}
async function environment(){const models=await Promise.all(['island_tree_01','shrub_01','rock_moss_set_01','fern_02'].map(n=>gltfLoader.loadAsync(`assets/${n}.glb`)));const [tree,shrub,rocks,fern]=models.map(g=>normalize(g.scene));
 for(const t of [tree,shrub,fern])t.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(!m.name.includes('bark'))windMaterial(m);if(m.map)m.map.anisotropy=4;});}});
 for(let i=0;i<(low?8:15);i++){const side=i%2?-1:1;plant(tree,side*(14+random()*9),-24+random()*47,12+random()*8,random()*6.28);}
 for(let i=0;i<(low?20:35);i++){const side=i%2?-1:1;plant(shrub,side*(10.7+random()*6),-23+random()*43,1.1+random()*1.8,random()*6.28);}
 for(let i=0;i<(low?30:65);i++){const side=i%2?-1:1;const x=side*(6.1+random()*3);const z=-1+random()*18;plant(fern,x,z,.45+random()*.65,random()*6.28);}
 for(let i=0;i<12;i++){const side=i%2?-1:1;plant(rocks,side*(10.9+random()*3),-21+random()*39,1.2+random()*2.7,random()*6.28);}
 for(let i=0;i<9;i++){const side=i%2?-1:1;const x=side*(4.5+random()*1),z=2+random()*12;plant(rocks,x,z,.28+random()*.30,random()*6.28);collider(x,z,1.9,1.5);}
}
function mist(){const positions=new Float32Array(130*3);for(let i=0;i<positions.length;i+=3){positions[i]=(random()-.5)*22;positions[i+1]=.2+random()*6;positions[i+2]=-24+random()*40;}const p=new T.Points(new T.BufferGeometry().setAttribute('position',new T.BufferAttribute(positions,3)),new T.PointsMaterial({color:0xd3c8a5,size:.035,opacity:.45,map:glowMap,transparent:true,depthWrite:false}));scene.add(p);return p;}
let dust;
function fail(e){failed=true;console.error(e);cancelAnimationFrame(frame);$('#welcome').hidden=true;$('#hud').hidden=true;$('#failure').hidden=false;}
try{[stone,sand,floor,soil]=await Promise.all([surface('mossy_stone_wall',.55),surface('mossy_sandstone',.45),surface('monastery_stone_floor',.5),surface('forest_ground_04',.7)]);stone.color.setScalar(.85);sand.color.setScalar(.82);floor.color.setScalar(.72);brass=new T.MeshStandardMaterial({color:0x746044,metalness:.76,roughness:.48});black=new T.MeshStandardMaterial({map:sand.map,normalMap:sand.normalMap,normalScale:new T.Vector2(.025,.025),color:0x171b18,roughness:.38,metalness:.04});
const hdr=await new RGBELoader(manager).loadAsync('assets/forest.hdr');hdr.mapping=T.EquirectangularReflectionMapping;const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromEquirectangular(hdr);scene.environment=env.texture;scene.environmentIntensity=.42;scene.background=hdr;scene.backgroundBlurriness=.2;scene.backgroundIntensity=.65;pmrem.dispose();
add(projectUV(new T.PlaneGeometry(150,150),.10),soil,[0,-.13,-7],[-Math.PI/2,0,0]);architecture();doors();for(const z of [9,2,-8,-15,-20])for(const x of [-2.7,2.7])torch(x,z);batches();await environment();dust=mist();assetsDone=true;$('#loading').textContent='The courtyard is ready.';$('#progress').value=100;$('#enter').disabled=false;renderer.shadowMap.needsUpdate=true;last=performance.now();animate(last);
}catch(e){fail(e);}
function blocked(x,z){if(x<-9.2||x>9.2||z>17||z<-21.2)return true;const r=.28;return obstacles.some(b=>Math.abs(x-b.x)<b.w+r&&Math.abs(z-b.z)<b.d+r);}
function activeMove(name){return touch.has(name)||({forward:['KeyW','ArrowUp'],back:['KeyS','ArrowDown'],left:['KeyA','ArrowLeft'],right:['KeyD','ArrowRight']}[name]||[]).some(k=>keys.has(k));}
function animate(t){if(failed)return;frame=requestAnimationFrame(animate);const dt=Math.min((t-last)/1000,.05)||.016;last=t;if(document.hidden)return;if(!paused)time+=dt;const modal=$('#controls').open;
 if(started&&!modal){let forward=Number(activeMove('forward'))-Number(activeMove('back')),right=Number(activeMove('right'))-Number(activeMove('left'));const len=Math.hypot(forward,right);if(len){forward/=len;right/=len;const speed=(keys.has('ShiftLeft')?3.9:2.2)*dt;const dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*right)*speed,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*right)*speed;if(!blocked(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(!blocked(camera.position.x,camera.position.z+dz))camera.position.z+=dz;}camera.position.y=T.MathUtils.damp(camera.position.y,camera.position.z<-3?2.1:1.76,8,dt);}
camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);for(const f of flames){f.scale.y=2.1+Math.sin(time*12+f.position.z)*.25;f.position.x+=Math.sin(time*8+f.position.z)*.00012;}lamps.forEach((l,i)=>l.intensity=9+Math.sin(time*8+i)*.6+Math.sin(time*17+i)*.25);wind.forEach(u=>u.value=time);if(dust)dust.rotation.y=Math.sin(time*.05)*.02;
const distance=Math.hypot(camera.position.x,camera.position.z+4.25),opening=1-T.MathUtils.smoothstep(distance,2.5,6);gates.forEach(g=>g.pivot.rotation.y=T.MathUtils.damp(g.pivot.rotation.y,-g.side*opening*1.57,3,dt));
$('#place').textContent=camera.position.z<-17?'The sacred sanctum':camera.position.z<-5?'The prayer hall':'The ancient courtyard';composer.render();Object.assign($('#view').dataset,{ready:String(assetsDone),position:camera.position.toArray().map(n=>n.toFixed(3)).join(','),triangles:String(renderer.info.render.triangles),calls:String(renderer.info.render.calls),time:time.toFixed(3),door:gates[0]?.pivot.rotation.y.toFixed(3)});}
$('#enter').onclick=()=>{started=true;$('#welcome').hidden=true;$('#hud').hidden=false;};$('#reset').onclick=()=>{camera.position.set(.8,1.76,16);yaw=.025;pitch=.06;keys.clear();touch.clear();};$('#quality').onclick=()=>{low=!low;ao.enabled=!low;renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.4));composer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.4));$('#quality').textContent=low?'Quality: light':'Quality: full';};if(low)$('#quality').textContent='Quality: light';
$('#pause').textContent=paused?'Resume atmosphere':'Pause atmosphere';$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'Resume atmosphere':'Pause atmosphere';$('#pause').setAttribute('aria-pressed',String(paused));};function controls(){keys.clear();touch.clear();$('#controls').showModal();}$('#help').onclick=controls;$('#close').onclick=()=>$('#controls').close();
addEventListener('keydown',e=>{if(e.code==='Escape'){if(!$('#controls').open){e.preventDefault();controls();}return;}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft'].includes(e.code)){if(started)e.preventDefault();keys.add(e.code);}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();touch.clear();drag=null;});document.addEventListener('visibilitychange',()=>{keys.clear();touch.clear();drag=null;});
renderer.domElement.addEventListener('pointerdown',e=>{if(!started||e.button>0)return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;yaw-=(e.clientX-drag.x)*.003;pitch=clamp(pitch-(e.clientY-drag.y)*.0026,-1.25,1.25);drag={x:e.clientX,y:e.clientY,id:e.pointerId};});for(const name of ['pointerup','pointercancel','lostpointercapture'])renderer.domElement.addEventListener(name,()=>drag=null);
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.move);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>touch.delete(b.dataset.move));});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fail(new Error('Graphics context lost'));});addEventListener('pagehide',()=>{cancelAnimationFrame(frame);draco.dispose();composer.dispose();renderer.dispose();});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});



