import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {TempleNavigation} from '../temple/navigation.js';
const $=s=>document.querySelector(s),clamp=THREE.MathUtils.clamp,smooth=THREE.MathUtils.smoothstep;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let failed=false;let paused=reduced.matches,low=innerWidth<700,playing=false,ready=false,progress=0,last=0,time=0,raf,disposed=false,forced=false,slow=0,lookX=0,lookY=0,drag=null,active=-1;
const renderer=new THREE.WebGLRenderer({antialias:!low,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=!low;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;$('#stage').append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Live 3D journey. Scroll to travel, or use the chapter buttons.');
const world=new THREE.Scene(),space=new THREE.Scene(),camera=new THREE.PerspectiveCamera(innerWidth<700?72:58,innerWidth/innerHeight,.08,700),spaceCamera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,1000);world.fog=new THREE.FogExp2(0xa49a87,.006);space.background=new THREE.Color(0x01040b);
const hemi=new THREE.HemisphereLight(0xacc9e9,0x62412b,1.1);world.add(hemi);const sun=new THREE.DirectionalLight(0xffd49b,3);sun.position.set(-20,45,-35);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-27,right:27,top:30,bottom:-28,near:1,far:130});sun.shadow.bias=-.0004;world.add(sun);const fill=new THREE.DirectionalLight(0x9fbcd7,1.2);fill.position.set(15,20,40);world.add(fill);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);world.environment=env.texture;world.environmentIntensity=.4;room.dispose();pmrem.dispose();
const sky=new THREE.Mesh(new THREE.SphereGeometry(400,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x162b40)},bottom:{value:new THREE.Color(0x9a7660)}},vertexShader:'varying vec3 v; void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 v;void main(){float h=normalize(v).y;vec3 c=mix(bottom,top,smoothstep(-.04,.65,h));float s=pow(max(0.,dot(normalize(v),normalize(vec3(.5,.2,-.8)))),180.);gl_FragColor=vec4(c+vec3(1.,.65,.25)*s*2.,1.);}'}));world.add(sky);
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,240,190,1)');g.addColorStop(.15,'rgba(255,198,100,.8)');g.addColorStop(.45,'rgba(235,164,80,.15)');g.addColorStop(1,'rgba(235,164,80,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c);}
const glowMap=glowTexture();const sunSprite=new THREE.Sprite(new THREE.SpriteMaterial({map:glowMap,color:0xffdd9a,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));sunSprite.position.set(70,40,-170);sunSprite.scale.set(22,22,1);world.add(sunSprite);
// Soft, irregular cloud volumes are generated procedurally, then moved in world space.
function cloudTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');let seed=38;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let i=0;i<38;i++){let cx=45+rand()*166,cy=75+rand()*106,r=25+rand()*48;const g=x.createRadialGradient(cx,cy,0,cx,cy,r);g.addColorStop(0,'rgba(242,230,212,.2)');g.addColorStop(.5,'rgba(230,222,205,.11)');g.addColorStop(1,'rgba(230,222,205,0)');x.fillStyle=g;x.fillRect(0,0,256,256);}return new THREE.CanvasTexture(c);}
const cloudMap=cloudTexture(),clouds=[];for(let i=0;i<64;i++){const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:cloudMap,transparent:true,depthWrite:false,opacity:.65,color:i%3===0?0xf9c58a:0xc3c9cc}));sprite.position.set(Math.sin(i*2.4)*65,18+(i%7)*2.1,-55+(i*13)%150);sprite.scale.set(30+(i%4)*8,19+(i%4)*5,1);sprite.userData.x=sprite.position.x;sprite.userData.phase=i;clouds.push(sprite);world.add(sprite);}
const starPositions=new Float32Array(1800*3);let seed=123;function rand(){seed=(seed*16807)%2147483647;return seed/2147483647;}for(let i=0;i<starPositions.length;i+=3){const a=rand()*Math.PI*2,b=Math.acos(2*rand()-1);starPositions[i]=Math.sin(b)*Math.cos(a)*380;starPositions[i+1]=Math.cos(b)*380;starPositions[i+2]=Math.sin(b)*Math.sin(a)*380;}const stars=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(starPositions,3)),new THREE.PointsMaterial({color:0xd3e6ff,size:.6,sizeAttenuation:true}));space.add(stars);
const globe=new THREE.Group();globe.position.set(17,-12,-35);space.add(globe);const earthMaterial=new THREE.MeshStandardMaterial({color:0x3977ad,roughness:.87,metalness:.02});const earth=new THREE.Mesh(new THREE.SphereGeometry(28,96,64),earthMaterial);earth.rotation.y=-1.75;globe.add(earth);space.add(new THREE.AmbientLight(0x607aaf,.4));const sunrise=new THREE.DirectionalLight(0xffe3b6,4);sunrise.position.set(-25,28,35);space.add(sunrise);
const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(28.65,64,48),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,blending:THREE.AdditiveBlending,depthWrite:false,vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n;varying vec3 v;void main(){float f=pow(1.-abs(dot(n,v)),3.);gl_FragColor=vec4(.16,.48,1.,f*.8);}'}));globe.add(atmosphere);
const earthSun=new THREE.Sprite(new THREE.SpriteMaterial({map:glowMap,blending:THREE.AdditiveBlending,depthWrite:false,color:0xffce8f}));earthSun.position.set(-5,12,-59);earthSun.scale.set(35,35,1);space.add(earthSun);
new THREE.TextureLoader().load('./assets/earth.jpg',texture=>{texture.colorSpace=THREE.SRGBColorSpace;earthMaterial.map=texture;earthMaterial.color.set(0xffffff);earthMaterial.needsUpdate=true;},undefined,()=>console.warn('Earth texture unavailable; using shaded globe.'));
const floor=new THREE.Mesh(new THREE.PlaneGeometry(450,450),new THREE.MeshStandardMaterial({color:0x514b40,roughness:.85}));floor.rotation.x=-Math.PI/2;floor.position.y=-.55;floor.receiveShadow=true;world.add(floor);
const draco=new DRACOLoader().setDecoderPath('../temple/vendor/draco/').setWorkerLimit(2),loader=new GLTFLoader().setDRACOLoader(draco);let playbackPosition=0;let model,rail,doors=[],lampLights=[],flameMaterials=[];
function instanceRepeated(root){root.updateMatrixWorld(true);const groups=new Map();root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;const materials=Array.isArray(o.material)?o.material:[o.material];for(const m of materials)if(/flame/i.test(m.name)&&!flameMaterials.includes(m))flameMaterials.push(m);const key=o.geometry.uuid+':'+materials.map(m=>m.uuid).join(',');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o);}});for(const meshes of groups.values()){if(meshes.length<3)continue;const first=meshes[0],inst=new THREE.InstancedMesh(first.geometry,first.material,meshes.length);meshes.forEach((m,i)=>{inst.setMatrixAt(i,m.matrixWorld);m.removeFromParent();});inst.castShadow=true;inst.receiveShadow=true;world.add(inst);}}
function tuneMaterials(root){const visited=new Set();root.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material]){if(visited.has(m))continue;visited.add(m);if(m.normalMap)m.normalScale.set(.14,.14);if(/granite|Basalt|Floor stone/i.test(m.name)){m.color.multiplyScalar(.48);m.roughness=.91;}if(/Sanctum black stone/i.test(m.name)){m.color.set(0x101316);m.roughness=.59;m.metalness=0;}if(/Antique brass/i.test(m.name)){m.roughness=.43;}m.needsUpdate=true;}});}
function createDoors(){const brass=new THREE.MeshStandardMaterial({color:0x8f5d20,metalness:.85,roughness:.32}),inset=new THREE.MeshStandardMaterial({color:0x312014,metalness:.4,roughness:.65});for(const side of [-1,1]){const hinge=new THREE.Group();hinge.position.set(side*1.45,.53,-9.18);const slab=new THREE.Mesh(new THREE.BoxGeometry(1.43,3.17,.12),brass);slab.position.set(-side*.715,1.59,0);hinge.add(slab);for(let row=0;row<4;row++){const panel=new THREE.Mesh(new THREE.BoxGeometry(1.10,.62,.035),inset);panel.position.set(-side*.715,.42+row*.77,.075);hinge.add(panel);const ring=new THREE.Mesh(new THREE.TorusGeometry(.20,.027,6,24),brass);ring.position.set(-side*.715,.42+row*.77,.106);hinge.add(ring);for(let n=0;n<8;n++){const boss=new THREE.Mesh(new THREE.SphereGeometry(.05,8,6),brass);boss.position.set(-side*.715+Math.cos(n*Math.PI/4)*.29,.42+row*.77+Math.sin(n*Math.PI/4)*.24,.12);hinge.add(boss);}}world.add(hinge);doors.push({hinge,side});}}
const particles=new THREE.Group();world.add(particles);const petalGeo=new THREE.PlaneGeometry(.06,.1),petalMat=new THREE.MeshStandardMaterial({color:0xbb3964,side:THREE.DoubleSide,roughness:.7});for(let i=0;i<44;i++){const petal=new THREE.Mesh(petalGeo,petalMat);petal.position.set((rand()-.5)*7,rand()*4,-7-rand()*9);petal.rotation.set(rand()*3,rand()*3,rand()*3);petal.userData.phase=rand()*6;particles.add(petal);}
const dustGeo=new THREE.BufferGeometry(),dustPos=new Float32Array(160*3);for(let i=0;i<dustPos.length;i+=3){dustPos[i]=(rand()-.5)*10;dustPos[i+1]=rand()*4;dustPos[i+2]=-15+rand()*19;}dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xffd694,map:glowMap,transparent:true,opacity:.7,size:.07,depthWrite:false,blending:THREE.AdditiveBlending}));world.add(dust);
const aim=new THREE.Vector3(),position=new THREE.Vector3(),maxScroll=()=>Math.max(1,document.documentElement.scrollHeight-innerHeight);function jump(p){playing=false;syncPlay();scrollTo({top:p*maxScroll(),behavior:reduced.matches?'instant':'smooth'});}function syncPlay(){$('#play').textContent=playing?'Pause journey':'Play journey';$('#play').setAttribute('aria-pressed',String(playing));}
const chapters=[['THE UNIVERSE','A divine journey<br>begins.','From the universe to your soul.'],['THE DESCENT','Through divine<br>clouds.','A higher call awaits.'],['THE TEMPLE','Revealed in<br>golden light.','A sacred place for all.'],['THE THRESHOLD','The doors<br>open.','Step into a world of divine energy.'],['THE SANCTUM','Om Namah<br>Shivaya.','Experience peace. Feel divinity. Find yourself.']];
function labels(p){const n=p<.18?0:p<.41?1:p<.90?2:p<.985?3:4;if(n===active)return;active=n;const c=chapters[n];$('#chapter').textContent=`0${n+1} / 05 · ${c[0]}`;$('#title').innerHTML=c[1];$('#description').textContent=c[2];$('#begin').hidden=n!==0;$('#end').hidden=n!==4;document.querySelectorAll('#stops button').forEach((b,i)=>i===n?b.setAttribute('aria-current','step'):b.removeAttribute('aria-current'));}
function render(t){if(disposed)return;raf=requestAnimationFrame(render);const dt=Math.min((t-last)/1000,.05)||.016;last=t;if(document.hidden||!ready)return;if(!low&&!forced&&dt>.035){if(++slow>150){low=true;quality();}}else slow=Math.max(0,slow-1);if(playing){playbackPosition=Math.min(maxScroll(),playbackPosition+dt*maxScroll()/70);scrollTo(0,playbackPosition);}if(playing&&scrollY>=maxScroll()-2){playing=false;syncPlay();}const wanted=clamp(scrollY/maxScroll(),0,1);progress=reduced.matches?wanted:THREE.MathUtils.damp(progress,wanted,5,dt);if(!paused)time+=dt;
 labels(progress);$('.progress span').style.width=`${progress*100}%`;const wash=(smooth(progress,.135,.19)*(1-smooth(progress,.20,.29)));$('#veil').style.opacity=String(wash*.98);earth.rotation.y=-1.75+time*.012;spaceCamera.position.set(-5+progress*15,8-progress*45,44-progress*150);spaceCamera.lookAt(14,-7,-35);
 if(progress<.41){const f=smooth(progress,.18,.41);camera.position.lerpVectors(new THREE.Vector3(0,52,83),new THREE.Vector3(0,3.3,34),f);aim.set(0,6,13);}else{const f=clamp((progress-.41)/.59,0,1);rail.sample(f*rail.rail.at(-1).distance,camera.position,aim);}
 if(progress>.84)aim.set(0,2,-13);camera.lookAt(aim);camera.rotation.order='YXZ';camera.rotation.y+=lookX;camera.rotation.x+=lookY;lookX=THREE.MathUtils.damp(lookX,0,1.2,dt);lookY=THREE.MathUtils.damp(lookY,0,1.2,dt);
 const interior=smooth(-camera.position.z,8,10.3);hemi.intensity=THREE.MathUtils.lerp(.7,.12,interior);fill.intensity=THREE.MathUtils.lerp(.55,.08,interior);sun.intensity=THREE.MathUtils.lerp(1.8,.3,interior);world.environmentIntensity=THREE.MathUtils.lerp(.22,.1,interior);world.fog.density=THREE.MathUtils.lerp(.006,.002,interior);
 const opening=smooth(-camera.position.z,5.5,8.5);for(const d of doors)d.hinge.rotation.y=-d.side*opening*1.48;
 clouds.forEach((c,i)=>{c.position.x=c.userData.x+Math.sin(time*.045+i)*5;c.material.opacity=.7*(1-smooth(progress,.37,.48));c.visible=progress<.48;});lampLights.forEach((l,i)=>l.intensity=l.userData.power*(1+.08*Math.sin(time*9+i)+.035*Math.sin(time*17+i*2)));flameMaterials.forEach(m=>m.emissiveIntensity=3.4+Math.sin(time*8)*.35);
 if(!paused){particles.children.forEach((p,i)=>{p.position.y-=dt*(.12+(i%4)*.025);if(p.position.y<.6)p.position.y=4;p.position.x+=Math.sin(time+p.userData.phase)*dt*.12;p.rotation.y+=dt*.4;p.rotation.z+=dt*.2;});dust.rotation.y=Math.sin(time*.1)*.018;}
 renderer.render(progress<.195?space:world,progress<.195?spaceCamera:camera);Object.assign($('#stage').dataset,{ready:'true',progress:progress.toFixed(4),position:camera.position.toArray().join(','),doorAngle:doors[0].hinge.rotation.y.toFixed(3),time:time.toFixed(3),calls:String(renderer.info.render.calls)});
}
function quality(){renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.5));renderer.shadowMap.enabled=!low;renderer.shadowMap.needsUpdate=true;particles.visible=!low;$('#quality').textContent=low?'Quality: light':'Quality: full';}
function fail(e){failed=true;console.error(e);ready=false;playing=false;cancelAnimationFrame(raf);$('#loading').hidden=true;$('#experience-ui').hidden=true;$('#failure').hidden=false;}
try{const timeout=setTimeout(()=>fail(new Error('Model load timed out')),45000);const gltf=await loader.loadAsync(low?'../temple/models/sri-shivan-alayam-mobile.glb':'../temple/models/sri-shivan-alayam.glb',e=>{const p=e.total?Math.round(e.loaded/e.total*100):50;$('#load-status').textContent=`Preparing the temple · ${p}%`;$('.load-line span').style.width=`${p}%`;});clearTimeout(timeout);if(failed)throw new Error("Loading was cancelled");model=gltf.scene;world.add(model);tuneMaterials(model);instanceRepeated(model);createDoors();
for(const [x,y,z,power]of [[0,3,-12,9],[-2,2,-8,15],[2,2,-8,15],[-3,2,7,25],[3,2,7,25],[0,3,-4,18]]){const light=new THREE.PointLight(0xffaf47,power,10,2);light.position.set(x,y,z);light.userData.power=power;world.add(light);lampLights.push(light);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowMap,color:0xffa53d,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,opacity:.35}));s.position.set(x,y-.5,z);s.scale.set(1.8,2.5,1);world.add(s);}
const stops=[['TEMPLE_ENTRANCE','','','',[0,6,13]],['COURTYARD','','','',[0,3,-3]],['MANDAPAM','','','',[0,2.3,-9]],['NANDI','','','',[0,1.9,-5.8]],['SANCTUM_ENTRANCE','','','',[0,1.9,-13]],['SHIVA_LINGAM','','','',[0,1.85,-13]]];rail=new TempleNavigation(camera,model,stops,{onStatus:()=>{},onArrival:()=>{},onMovement:()=>{},reducedMotion:()=>reduced.matches});ready=true;$('#loading').hidden=true;$('#experience-ui').hidden=false;quality();last=performance.now();render(last);
}catch(e){fail(e);}
$('#begin').onclick=()=>{playing=true;syncPlay();};$('#play').onclick=()=>{if(progress>.999)scrollTo(0,0);playing=!playing;syncPlay();};document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>jump(Number(b.dataset.p)));function updateMotion(){$('#motion').textContent=paused?'Resume atmosphere':'Pause atmosphere';$('#motion').setAttribute('aria-pressed',String(paused));}updateMotion();$('#motion').onclick=()=>{paused=!paused;updateMotion();};reduced.addEventListener('change',e=>{paused=e.matches;updateMotion();});$('#quality').onclick=()=>{forced=true;low=!low;quality();};
function stopPlayback(){playing=false;syncPlay();}addEventListener('wheel',stopPlayback,{passive:true});addEventListener('touchstart',stopPlayback,{passive:true});addEventListener('keydown',e=>{if(e.key==='Escape'||e.key==='PageDown'||e.key==='PageUp'||e.key.startsWith('Arrow'))stopPlayback();});renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;lookX=clamp(lookX+(e.clientX-drag.x)*.002,-.55,.55);lookY=clamp(lookY+(e.clientY-drag.y)*.002,-.3,.3);drag={x:e.clientX,y:e.clientY};});for(const event of ['pointerup','pointercancel','lostpointercapture'])renderer.domElement.addEventListener(event,()=>drag=null);
addEventListener('resize',()=>{camera.aspect=spaceCamera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?72:58;camera.updateProjectionMatrix();spaceCamera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fail(new Error('Graphics context lost'));});addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);draco.dispose();env.dispose();const gs=new Set(),ms=new Set(),ts=new Set();for(const s of [world,space])s.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>ms.add(m));});gs.forEach(g=>g.dispose());ms.forEach(m=>{Object.values(m).forEach(v=>{if(v?.isTexture)ts.add(v);});m.dispose();});ts.forEach(t=>t.dispose());renderer.dispose();});addEventListener('pageshow',e=>{if(e.persisted)location.reload();});



