'use strict';
document.documentElement.classList.add('enhanced');
const paths={temple:'M4 36h32M8 36V28h24v8M10 28v-6h20v6M12 22v-6h16v6M15 16v-6h10v6M18 10V5h4v5M20 2v3M16 36v-7h8v7M14 25h2m8 0h2M16 19h2m4 0h2M19 13h2',lotus:'M20 32C9 24 15 12 20 5c5 7 11 19 0 27ZM20 32C7 33 3 22 4 15c8 1 12 5 16 17Zm0 0c13 1 17-10 16-17-8 1-12 5-16 17ZM20 32C8 38 2 29 2 25m18 7c12 6 18-3 18-7',calendar:'M6 9h28v26H6ZM6 17h28M13 5v8m14-8v8M12 23h3m4 0h3m4 0h3m-17 6h3m4 0h3m4 0h3',gallery:'M5 7h30v27H5Zm1 23 9-9 6 6 5-8 9 11M14 12a3 3 0 1 0 0 6 3 3 0 0 0 0-6',heart:'M20 35 6 21C-4 8 13 0 20 12 27 0 44 8 34 21Z',live:'M20 16a3 3 0 1 0 0 6 3 3 0 0 0 0-6m0 8-5 12h10Zm-8-12a12 12 0 0 1 0-15m16 0a12 12 0 0 1 0 15M7 7a19 19 0 0 0 0 25M33 7a19 19 0 0 1 0 25',pin:'M20 37S7 23 7 15a13 13 0 1 1 26 0c0 8-13 22-13 22ZM20 11a4 4 0 1 0 0 8 4 4 0 0 0 0-8'};
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 40 40');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]);svg.append(p);return svg;}
document.querySelectorAll('[data-icon]').forEach(a=>a.prepend(icon(a.dataset.icon)));document.querySelector('.brand span').replaceWith(icon('temple'));
const menu=document.querySelector('#menu'),nav=document.querySelector('#nav');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);};nav.onclick=e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');}};
const dialog=document.querySelector('dialog');
for(const [name,title]of Object.entries({earth:'From the universe',clouds:'A higher call',temple:'Golden light',doors:'The doors open',sanctum:'The sacred sanctum',nandi:'A place for every soul'})){const f=document.createElement('figure'),img=document.createElement('img'),c=document.createElement('figcaption');img.src=`cinematic/assets/${name}.webp`;img.alt=title;img.loading='lazy';c.textContent=title;f.append(img,c);document.querySelector('.gallery-grid').append(f);}
document.querySelectorAll('[data-info]').forEach(a=>a.onclick=e=>{e.preventDefault();stop();const content=document.querySelector(a.hash).cloneNode(true);content.removeAttribute('id');content.querySelector('h2').id='dialog-title';dialog.querySelector('.dialog-body').replaceChildren(content);dialog.showModal();});
dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();};
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),motion=document.querySelector('#motion');let paused=reduced.matches;try{paused=paused||localStorage.getItem('temple-motion')==='paused';}catch{}function update(){document.documentElement.classList.toggle('paused',paused);motion.setAttribute('aria-pressed',String(paused));motion.textContent=paused?'Resume motion':'Pause motion';}update();motion.onclick=()=>{paused=!paused;update();try{localStorage.setItem('temple-motion',paused?'paused':'playing');}catch{}};reduced.onchange=e=>{paused=e.matches;update();};
const visible=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.05});document.querySelectorAll('.scene').forEach(el=>visible.observe(el));
const progress=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)document.querySelectorAll('.stages a').forEach(a=>{if(a.hash===`#${e.target.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-35% 0px -35% 0px'});document.querySelectorAll('main>section[id],#explore').forEach(el=>progress.observe(el));
let timer;const controls=document.querySelector('.tour-controls');function stop(){clearTimeout(timer);controls.hidden=true;document.querySelector('#intro').setAttribute('aria-pressed','false');}document.querySelector('#intro').onclick=()=>{stop();controls.hidden=false;document.querySelector('#intro').setAttribute('aria-pressed','true');const stops=['space','clouds','temple','enter','sanctum','explore'];let n=0;function next(){document.getElementById(stops[n++]).scrollIntoView({behavior:paused||reduced.matches?'instant':'smooth',block:'start'});timer=setTimeout(n<stops.length?next:stop,5500);}next();};document.querySelector('#stop').onclick=stop;document.addEventListener('keydown',e=>{if(e.key==='Escape')stop();});window.addEventListener('wheel',stop,{passive:true});window.addEventListener('touchstart',stop,{passive:true});document.querySelectorAll('a[href^="#"]:not([data-info])').forEach(a=>a.addEventListener('click',stop));
